// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFiir8-134YIkGse2-oNcJ5YxrGldpPYE',
    appId: '1:1023857343181:web:d70ef886a757a91ace4784',
    messagingSenderId: '1023857343181',
    projectId: 'authlearning-9cc54',
    authDomain: 'authlearning-9cc54.firebaseapp.com',
    storageBucket: 'authlearning-9cc54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVRLt7zdWOtAll4R7a3yMe1_srzGLBB44',
    appId: '1:1023857343181:android:b634a0ee9bafe045ce4784',
    messagingSenderId: '1023857343181',
    projectId: 'authlearning-9cc54',
    storageBucket: 'authlearning-9cc54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByu3WPkzb0ZZTCFMqnOWupPRidAkpnQac',
    appId: '1:1023857343181:ios:7464fa3c6f27ff08ce4784',
    messagingSenderId: '1023857343181',
    projectId: 'authlearning-9cc54',
    storageBucket: 'authlearning-9cc54.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByu3WPkzb0ZZTCFMqnOWupPRidAkpnQac',
    appId: '1:1023857343181:ios:7464fa3c6f27ff08ce4784',
    messagingSenderId: '1023857343181',
    projectId: 'authlearning-9cc54',
    storageBucket: 'authlearning-9cc54.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFiir8-134YIkGse2-oNcJ5YxrGldpPYE',
    appId: '1:1023857343181:web:4cb811039b6e3498ce4784',
    messagingSenderId: '1023857343181',
    projectId: 'authlearning-9cc54',
    authDomain: 'authlearning-9cc54.firebaseapp.com',
    storageBucket: 'authlearning-9cc54.firebasestorage.app',
  );

}